import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

// Geist Variable Font (for regular text)
const geist = localFont({
  src: "../public/fonts/GeistVF.woff",
  variable: "--font-geist",
});

// Geist Mono Variable Font (for monospace/code)
const geistMono = localFont({
  src: "../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Registration Form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geist.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
